export const countryCodes: {
  [key: string]: { name: string; nagarCode: string };
} = {
  AF: { name: "AFGHANISTAN", nagarCode: "NA" },
  AX: { name: "ÅLAND ISLANDS", nagarCode: "AX" },
  AL: { name: "ALBANIA", nagarCode: "AL" },
  DZ: { name: "ALGERIA", nagarCode: "NA" },
  AS: { name: "AMERICAN SAMOA", nagarCode: "NA" },
  AD: { name: "ANDORRA", nagarCode: "AD" },
  AO: { name: "ANGOLA", nagarCode: "NA" },
  AI: { name: "ANGUILLA", nagarCode: "NA" },
  AQ: { name: "ANTARCTICA", nagarCode: "NA" },
  AG: { name: "ANTIGUA AND BARBUDA", nagarCode: "NA" },
  AR: { name: "ARGENTINA", nagarCode: "AR" },
  AM: { name: "ARMENIA", nagarCode: "AM" },
  AW: { name: "ARUBA", nagarCode: "NA" },
  AU: { name: "AUSTRALIA", nagarCode: "AU" },
  AT: { name: "AUSTRIA", nagarCode: "AT" },
  AZ: { name: "AZERBAIJAN", nagarCode: "NA" },
  BS: { name: "BAHAMAS", nagarCode: "BS" },
  BH: { name: "BAHRAIN", nagarCode: "NA" },
  BD: { name: "BANGLADESH", nagarCode: "NA" },
  BB: { name: "BARBADOS", nagarCode: "BB" },
  BY: { name: "BELARUS", nagarCode: "BY" },
  BE: { name: "BELGIUM", nagarCode: "BE" },
  BZ: { name: "BELIZE", nagarCode: "BZ" },
  BJ: { name: "BENIN", nagarCode: "BJ" },
  BM: { name: "BERMUDA", nagarCode: "NA" },
  BT: { name: "BHUTAN", nagarCode: "NA" },
  BO: { name: "BOLIVIA, PLURINATIONAL STATE OF", nagarCode: "BO" },
  BQ: { name: "BONAIRE, SINT EUSTATIUS AND SABA", nagarCode: "NA" },
  BA: { name: "BOSNIA AND HERZEGOVINA", nagarCode: "BA" },
  BW: { name: "BOTSWANA", nagarCode: "BW" },
  BV: { name: "BOUVET ISLAND", nagarCode: "NA" },
  BR: { name: "BRAZIL", nagarCode: "BR" },
  IO: { name: "BRITISH INDIAN OCEAN TERRITORY", nagarCode: "NA" },
  BN: { name: "BRUNEI DARUSSALAM", nagarCode: "NA" },
  BG: { name: "BULGARIA", nagarCode: "BG" },
  BF: { name: "BURKINA FASO", nagarCode: "NA" },
  BI: { name: "BURUNDI", nagarCode: "NA" },
  KH: { name: "CAMBODIA", nagarCode: "NA" },
  CM: { name: "CAMEROON", nagarCode: "NA" },
  CA: { name: "CANADA", nagarCode: "CA" },
  CV: { name: "CAPE VERDE", nagarCode: "NA" },
  KY: { name: "CAYMAN ISLANDS", nagarCode: "NA" },
  CF: { name: "CENTRAL AFRICAN REPUBLIC", nagarCode: "NA" },
  TD: { name: "CHAD", nagarCode: "NA" },
  CL: { name: "CHILE", nagarCode: "CL" },
  CN: { name: "CHINA", nagarCode: "CN" },
  CX: { name: "CHRISTMAS ISLAND", nagarCode: "NA" },
  CC: { name: "COCOS (KEELING) ISLANDS", nagarCode: "NA" },
  CO: { name: "COLOMBIA", nagarCode: "CO" },
  KM: { name: "COMOROS", nagarCode: "NA" },
  CG: { name: "CONGO", nagarCode: "NA" },
  CD: { name: "CONGO, THE DEMOCRATIC REPUBLIC OF THE", nagarCode: "NA" },
  CK: { name: "COOK ISLANDS", nagarCode: "NA" },
  CR: { name: "COSTA RICA", nagarCode: "CR" },
  CI: { name: "CÔTE D’IVOIRE", nagarCode: "NA" },
  HR: { name: "CROATIA", nagarCode: "HR" },
  CU: { name: "CUBA", nagarCode: "CU" },
  CW: { name: "CURAÇAO", nagarCode: "NA" },
  CY: { name: "CYPRUS", nagarCode: "CY" },
  CZ: { name: "CZECH REPUBLIC", nagarCode: "CZ" },
  DK: { name: "DENMARK", nagarCode: "DK" },
  DJ: { name: "DJIBOUTI", nagarCode: "NA" },
  DM: { name: "DOMINICA", nagarCode: "NA" },
  DO: { name: "DOMINICAN REPUBLIC", nagarCode: "DO" },
  EC: { name: "ECUADOR", nagarCode: "EC" },
  EG: { name: "EGYPT", nagarCode: "EG" },
  SV: { name: "EL SALVADOR", nagarCode: "SV" },
  GQ: { name: "EQUATORIAL GUINEA", nagarCode: "NA" },
  ER: { name: "ERITREA", nagarCode: "NA" },
  EE: { name: "ESTONIA", nagarCode: "EE" },
  ET: { name: "ETHIOPIA", nagarCode: "NA" },
  FK: { name: "FALKLAND ISLANDS (MALVINAS)", nagarCode: "NA" },
  FO: { name: "FAROE ISLANDS", nagarCode: "FO" },
  FJ: { name: "FIJI", nagarCode: "NA" },
  FI: { name: "FINLAND", nagarCode: "FI" },
  FR: { name: "FRANCE", nagarCode: "FR" },
  GF: { name: "FRENCH GUIANA", nagarCode: "NA" },
  PF: { name: "FRENCH POLYNESIA", nagarCode: "NA" },
  TF: { name: "FRENCH SOUTHERN TERRITORIES", nagarCode: "NA" },
  GA: { name: "GABON", nagarCode: "GA" },
  GM: { name: "GAMBIA", nagarCode: "GM" },
  GE: { name: "GEORGIA", nagarCode: "GE" },
  DE: { name: "GERMANY", nagarCode: "DE" },
  GH: { name: "GHANA", nagarCode: "NA" },
  GI: { name: "GIBRALTAR", nagarCode: "GI" },
  GR: { name: "GREECE", nagarCode: "GR" },
  GL: { name: "GREENLAND", nagarCode: "GL" },
  GD: { name: "GRENADA", nagarCode: "GD" },
  GP: { name: "GUADELOUPE", nagarCode: "NA" },
  GU: { name: "GUAM", nagarCode: "NA" },
  GT: { name: "GUATEMALA", nagarCode: "GT" },
  GG: { name: "GUERNSEY", nagarCode: "GG" },
  GN: { name: "GUINEA", nagarCode: "NA" },
  GW: { name: "GUINEA-BISSAU", nagarCode: "NA" },
  GY: { name: "GUYANA", nagarCode: "GY" },
  HT: { name: "HAITI", nagarCode: "HT" },
  HM: { name: "HEARD ISLAND AND MCDONALD ISLANDS", nagarCode: "NA" },
  VA: { name: "HOLY SEE (VATICAN CITY STATE)", nagarCode: "VA" },
  HN: { name: "HONDURAS", nagarCode: "HN" },
  HK: { name: "HONG KONG", nagarCode: "HK" },
  HU: { name: "HUNGARY", nagarCode: "HU" },
  IS: { name: "ICELAND", nagarCode: "IS" },
  IN: { name: "INDIA", nagarCode: "NA" },
  ID: { name: "INDONESIA", nagarCode: "ID" },
  IR: { name: "IRAN, ISLAMIC REPUBLIC OF", nagarCode: "NA" },
  IQ: { name: "IRAQ", nagarCode: "NA" },
  IE: { name: "IRELAND", nagarCode: "IE" },
  IM: { name: "ISLE OF MAN", nagarCode: "IM" },
  IL: { name: "ISRAEL", nagarCode: "NA" },
  IT: { name: "ITALY", nagarCode: "IT" },
  JM: { name: "JAMAICA", nagarCode: "JM" },
  JP: { name: "JAPAN", nagarCode: "JP" },
  JE: { name: "JERSEY", nagarCode: "JE" },
  JO: { name: "JORDAN", nagarCode: "NA" },
  KZ: { name: "KAZAKHSTAN", nagarCode: "KZ" },
  KE: { name: "KENYA", nagarCode: "NA" },
  KI: { name: "KIRIBATI", nagarCode: "NA" },
  KP: { name: "KOREA, DEMOCRATIC PEOPLE’S REPUBLIC OF", nagarCode: "NA" },
  KR: { name: "KOREA, REPUBLIC OF", nagarCode: "KR" },
  KW: { name: "KUWAIT", nagarCode: "NA" },
  KG: { name: "KYRGYZSTAN", nagarCode: "NA" },
  LA: { name: "LAO PEOPLE’S DEMOCRATIC REPUBLIC", nagarCode: "NA" },
  LV: { name: "LATVIA", nagarCode: "LV" },
  LB: { name: "LEBANON", nagarCode: "NA" },
  LS: { name: "LESOTHO", nagarCode: "LS" },
  LR: { name: "LIBERIA", nagarCode: "NA" },
  LY: { name: "LIBYA", nagarCode: "NA" },
  LI: { name: "LIECHTENSTEIN", nagarCode: "LI" },
  LT: { name: "LITHUANIA", nagarCode: "LT" },
  LU: { name: "LUXEMBOURG", nagarCode: "LU" },
  MO: { name: "MACAO", nagarCode: "NA" },
  MK: { name: "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", nagarCode: "MK" },
  MG: { name: "MADAGASCAR", nagarCode: "MG" },
  MW: { name: "MALAWI", nagarCode: "NA" },
  MY: { name: "MALAYSIA", nagarCode: "NA" },
  MV: { name: "MALDIVES", nagarCode: "NA" },
  ML: { name: "MALI", nagarCode: "NA" },
  MT: { name: "MALTA", nagarCode: "MT" },
  MH: { name: "MARSHALL ISLANDS", nagarCode: "NA" },
  MQ: { name: "MARTINIQUE", nagarCode: "NA" },
  MR: { name: "MAURITANIA", nagarCode: "NA" },
  MU: { name: "MAURITIUS", nagarCode: "NA" },
  YT: { name: "MAYOTTE", nagarCode: "NA" },
  MX: { name: "MEXICO", nagarCode: "MX" },
  FM: { name: "MICRONESIA, FEDERATED STATES OF", nagarCode: "NA" },
  MD: { name: "MOLDOVA, REPUBLIC OF", nagarCode: "MD" },
  MC: { name: "MONACO", nagarCode: "MC" },
  MN: { name: "MONGOLIA", nagarCode: "MN" },
  ME: { name: "MONTENEGRO", nagarCode: "ME" },
  MS: { name: "MONTSERRAT", nagarCode: "MS" },
  MA: { name: "MOROCCO", nagarCode: "MA" },
  MZ: { name: "MOZAMBIQUE", nagarCode: "MZ" },
  MM: { name: "MYANMAR", nagarCode: "NA" },
  NA: { name: "NAMIBIA", nagarCode: "NA" },
  NR: { name: "NAURU", nagarCode: "NA" },
  NP: { name: "NEPAL", nagarCode: "NA" },
  NL: { name: "NETHERLANDS", nagarCode: "NL" },
  NC: { name: "NEW CALEDONIA", nagarCode: "NA" },
  NZ: { name: "NEW ZEALAND", nagarCode: "NZ" },
  NI: { name: "NICARAGUA", nagarCode: "NI" },
  NE: { name: "NIGER", nagarCode: "NE" },
  NG: { name: "NIGERIA", nagarCode: "NG" },
  NU: { name: "NIUE", nagarCode: "NA" },
  NF: { name: "NORFOLK ISLAND", nagarCode: "NA" },
  MP: { name: "NORTHERN MARIANA ISLANDS", nagarCode: "NA" },
  NO: { name: "NORWAY", nagarCode: "NO" },
  OM: { name: "OMAN", nagarCode: "NA" },
  PK: { name: "PAKISTAN", nagarCode: "NA" },
  PW: { name: "PALAU", nagarCode: "NA" },
  PS: { name: "PALESTINE, STATE OF", nagarCode: "NA" },
  PA: { name: "PANAMA", nagarCode: "PA" },
  PG: { name: "PAPUA NEW GUINEA", nagarCode: "PG" },
  PY: { name: "PARAGUAY", nagarCode: "PY" },
  PE: { name: "PERU", nagarCode: "PE" },
  PH: { name: "PHILIPPINES", nagarCode: "NA" },
  PN: { name: "PITCAIRN", nagarCode: "NA" },
  PL: { name: "POLAND", nagarCode: "PL" },
  PT: { name: "PORTUGAL", nagarCode: "PT" },
  PR: { name: "PUERTO RICO", nagarCode: "PR" },
  QA: { name: "QATAR", nagarCode: "NA" },
  RE: { name: "RÉUNION", nagarCode: "NA" },
  RO: { name: "ROMANIA", nagarCode: "RO" },
  RU: { name: "RUSSIAN FEDERATION", nagarCode: "RU" },
  RW: { name: "RWANDA", nagarCode: "NA" },
  BL: { name: "SAINT BARTHÉLEMY", nagarCode: "NA" },
  SH: { name: "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA", nagarCode: "NA" },
  KN: { name: "SAINT KITTS AND NEVIS", nagarCode: "NA" },
  LC: { name: "SAINT LUCIA", nagarCode: "NA" },
  MF: { name: "SAINT MARTIN (FRENCH PART)", nagarCode: "NA" },
  PM: { name: "SAINT PIERRE AND MIQUELON", nagarCode: "NA" },
  VC: { name: "SAINT VINCENT AND THE GRENADINES", nagarCode: "NA" },
  WS: { name: "SAMOA", nagarCode: "NA" },
  SM: { name: "SAN MARINO", nagarCode: "SM" },
  ST: { name: "SAO TOME AND PRINCIPE", nagarCode: "NA" },
  SA: { name: "SAUDI ARABIA", nagarCode: "NA" },
  SN: { name: "SENEGAL", nagarCode: "NA" },
  RS: { name: "SERBIA", nagarCode: "RS" },
  SC: { name: "SEYCHELLES", nagarCode: "NA" },
  SL: { name: "SIERRA LEONE", nagarCode: "NA" },
  SG: { name: "SINGAPORE", nagarCode: "SG" },
  SX: { name: "SINT MAARTEN (DUTCH PART)", nagarCode: "NA" },
  SK: { name: "SLOVAKIA", nagarCode: "SK" },
  SI: { name: "SLOVENIA", nagarCode: "SI" },
  SB: { name: "SOLOMON ISLANDS", nagarCode: "NA" },
  SO: { name: "SOMALIA", nagarCode: "NA" },
  ZA: { name: "SOUTH AFRICA", nagarCode: "ZA" },
  GS: { name: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", nagarCode: "NA" },
  SS: { name: "SOUTH SUDAN", nagarCode: "NA" },
  ES: { name: "SPAIN", nagarCode: "ES" },
  LK: { name: "SRI LANKA", nagarCode: "NA" },
  SD: { name: "SUDAN", nagarCode: "NA" },
  SR: { name: "SURINAME", nagarCode: "SR" },
  SJ: { name: "SVALBARD AND JAN MAYEN", nagarCode: "SJ" },
  SZ: { name: "SWAZILAND", nagarCode: "NA" },
  SE: { name: "SWEDEN", nagarCode: "SE" },
  CH: { name: "SWITZERLAND", nagarCode: "CH" },
  SY: { name: "SYRIAN ARAB REPUBLIC", nagarCode: "NA" },
  TW: { name: "TAIWAN, PROVINCE OF CHINA", nagarCode: "NA" },
  TJ: { name: "TAJIKISTAN", nagarCode: "NA" },
  TZ: { name: "TANZANIA, UNITED REPUBLIC OF", nagarCode: "NA" },
  TH: { name: "THAILAND", nagarCode: "NA" },
  TL: { name: "TIMOR-LESTE", nagarCode: "NA" },
  TG: { name: "TOGO", nagarCode: "NA" },
  TK: { name: "TOKELAU", nagarCode: "NA" },
  TO: { name: "TONGA", nagarCode: "NA" },
  TT: { name: "TRINIDAD AND TOBAGO", nagarCode: "NA" },
  TN: { name: "TUNISIA", nagarCode: "TN" },
  TR: { name: "TURKEY", nagarCode: "TR" },
  TM: { name: "TURKMENISTAN", nagarCode: "NA" },
  TC: { name: "TURKS AND CAICOS ISLANDS", nagarCode: "NA" },
  TV: { name: "TUVALU", nagarCode: "NA" },
  UG: { name: "UGANDA", nagarCode: "NA" },
  UA: { name: "UKRAINE", nagarCode: "UA" },
  AE: { name: "UNITED ARAB EMIRATES", nagarCode: "NA" },
  GB: { name: "UNITED KINGDOM", nagarCode: "GB" },
  US: { name: "UNITED STATES", nagarCode: "US" },
  UM: { name: "UNITED STATES MINOR OUTLYING ISLANDS", nagarCode: "NA" },
  UY: { name: "URUGUAY", nagarCode: "UY" },
  UZ: { name: "UZBEKISTAN", nagarCode: "NA" },
  VU: { name: "VANUATU", nagarCode: "NA" },
  VE: { name: "VENEZUELA, BOLIVARIAN REPUBLIC OF", nagarCode: "VE" },
  VN: { name: "VIET NAM", nagarCode: "VN" },
  VG: { name: "VIRGIN ISLANDS, BRITISH", nagarCode: "NA" },
  VI: { name: "VIRGIN ISLANDS, U.S.", nagarCode: "NA" },
  WF: { name: "WALLIS AND FUTUNA", nagarCode: "NA" },
  EH: { name: "WESTERN SAHARA", nagarCode: "NA" },
  YE: { name: "YEMEN", nagarCode: "NA" },
  ZM: { name: "ZAMBIA", nagarCode: "NA" },
  ZW: { name: "ZIMBABWE", nagarCode: "ZW" },
};
